baseURL: "https://jiangfucheng.github.io/"
title: Fucheng Jiang's Blog
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                # - name: Archive
                #   url: archives
                #   weight: 5
                # - name: Search
                #   url: search/
                #   weight: 10
                # - name: Tags
                #   url: tags/
                #   weight: 10
                - name: Posts
                  url: posts/
                  weight: 10
                - name: About
                  url: about
                  weight: 10
                
outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    # description: "Theme PaperMod - https://github.com/jiangfucheng"
    author: Fucheng Jiang

    defaultTheme: dark 
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    ShowWordCount: true
    comments: true
    # comments: false
    images: ["papermod-cover.png"]

    profileMode:
        enabled: false

    homeInfoParams:
        Title: "Fucheng Jiang's Blog"
        Content: >
            Welcome to Fucheng Jiang's Blog.

    socialIcons:
        - name: github
          url: "https://github.com/jiangfucheng"
        - name: Rss
          url: "index.xml"

    # editPost:
    #     URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
    #     Text: "Suggest Changes" # edit text
    #     appendFilePath: true # to append file path to Edit link

    assets:
        disableHLJS: false


markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai
